/**
 * GENERATED by `scripts/gen-persistence-catalog.ts` — do not edit by hand; run
 * `pnpm run gen-persistence-catalog` to regenerate (verified fresh by
 * `pnpm run verify-persistence-catalog`, part of `doc-sync`).
 * @module @deepseek-ai/dsh-session/known-event-types
 */

/**
 * Every `SessionEventMap` member declared in this repository — the event
 * vocabulary this build understands. The persistence read path refuses to
 * interpret a log containing a type outside this set unless the event
 * carries the envelope's `ignorable` marker (see `SessionEvent.ignorable`
 * in `./types.ts`) or its active owner registered the type through
 * `ctx.sessionEventTypes` before the read: such a log was likely written
 * by a newer harness, and silently skipping a required event would
 * reconstruct a wrong session.
 * Downstream (out-of-repo) plugin events are outside this list by
 * construction. The persisted `SessionEvent.ignorable` marker is the
 * first-party compatibility mechanism; `ctx.sessionEventTypes` is the
 * admission seam for out-of-repo required types. The rationales are in
 * `.agents/notes/implemented/architecture/2026-08-30-retain-ignorable-external-session-events.md`
 * and `.agents/notes/implemented/architecture/2026-08-28-session-event-registration.md`.
 */
export const KNOWN_SESSION_EVENT_TYPES: ReadonlySet<string> = new Set([
  'agent-preset/selected',
  'agent/inbox/spliced',
  'approval/asked',
  'approval/decided',
  'approval/policy',
  'assistant/chunk',
  'assistant/message',
  'command/done',
  'command/run',
  'compaction/end',
  'compaction/prune',
  'compaction/start',
  'compaction/summary',
  'feedback/record',
  'goal/change',
  'hook/invoked',
  'hook/result',
  'llm/retry',
  'llm/retry-started',
  'model/selection',
  'permission/preset',
  'plan/mode',
  'request/context',
  'request/header',
  'sandbox/mode',
  'schedule/change',
  'session-log-deepseek/delivery-accepted',
  'session/end-seed',
  'session/title',
  'session/title-llm-request',
  'step/end',
  'step/start',
  'subagent/descriptor',
  'subagent/model-selection-default',
  'subagent/model-selection-policy',
  'subagent/runtime-provider-selection',
  'team/member',
  'team/message/delivered',
  'team/message/queued',
  'team/task',
  'todo/write',
  'tool-workflow/agent-end',
  'tool-workflow/agent-start',
  'tool-workflow/run-end',
  'tool-workflow/run-start',
  'tool/call',
  'tool/code-dispatch',
  'tool/code-dispatch-start',
  'tool/result',
  'turn/end',
  'turn/start',
  'user/message',
  'web/deepseek-search-llm-request',
])
